In [167]:
'''
Task 4.1
Creating Arrays
'''
from __future__ import print_function
import numpy as np

l= [1,2,3,4,5]
# creating 1d array
array1 = np.array(l)
print(array1)

# lists of list
data= [range(1,5), range(5,9)]
# creating a 2d array
array2= np.array(data)
# print(data)
print(array2)

# converting array back to list
array2.tolist()

#create special arrays
np.zeros(10)
np.zeros((3, 6))
np.ones(10)
# 0 to 1 (inclusive) with 5 points
np.linspace(0,1,5)
# # 10^0 to 10^3 (inclusive) with 4 points
np.logspace(0,3,4)

#arange is like  range, except it returns an array (not a list)
int_array = np.arange(5)
float_array = int_array.astype(float)
print(array2)


[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [21]:
# Task 4.2 Examining arrays
array1.dtype # float 64

array2.dtype # int32
# the following function will give the dimention of the array
array2.ndim 
# the following function will give the dimension in (row, column)
array2.shape # (2,4) - axis 0 is rows, axis 1 is columns


(2, 4)

In [25]:
# Task 4.4 Stack arrays
# stack flat arrays in columns
a = np.array([0,1])
b = np.array([2,3])

# stack will put the two arrays in column , stack on top of eachother
ab = np.stack((a,b)).T
print(ab)

# Another way of doing it

np.hstack((a[:, None], b[:,None]))


[[0 2]
 [1 3]]


array([[0, 2],
       [1, 3]])

In [39]:
#4.5 Selection 
#single item

arr = np.arange(10, dtype=float).reshape((2,5))
print(arr)


arr[0] # This will return the first element of the array
arr[0,3] # it return the element of 0 row and column 3 (the row and column numbered from zero)
# alternate method of doing the same thing as above
arr[0][3]


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


3.0

In [72]:
# 4.5.1 Slicing
#Syntax:start:stop: step with start (default 0) stop (default 1)

#row 0: returns 1d array 

arr[0, :] 

# return an array consists of elements from "0 column" (1st count)
arr[:, 0]

# return an array consists of elements from "2 column" (3rd count)
arr[:,2]


# return an array from "2 column" (3rd count) onwards
arr[:,2:]
print(arr)
print(arr[:,2:])

# return an array from "1 column" (2ndcount) onwards
''' array1 =
[[1 2 3 4]
 [5 6 7 8]]'''
array2 = arr[: , 1:4]
array2



[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[2. 3. 4.]
 [7. 8. 9.]]


array([[1., 2., 3.],
       [6., 7., 8.]])

In [168]:
#4.6 Vectorized Operations

nums = np.arange(5)
nums * 10                # multiply each by 10
nums  = np.sqrt (nums) # square root of each element
np.ceil(nums)         # also floor, rint (round the nearest int)
np.isnan(nums)       # checks for NaN
nums +np.arange(5)   # add element -wise
np.maximum(nums, np.array([1, -2, 3, -4, 5])) # compare elemnt -wise

# compare Euclidean distance between 2 vectors
vec1 = np.random.randn(10) # creating an array of random floats
vec2 = np.random.randn(10) 
dist = np.sqrt(np.sum((vec1-vec2)**2))
print(dist)

# math and stats
rnd = np.random.randn(4, 2) # creating a random array 4X2
rnd.mean()
rnd.std()
rnd.argmin()         # index of minimum element
rnd.sum()
rnd.sum(axis=0)      # sum of columns
rnd.sum(axis=1)     # sum of rows

# methods for boolean arrays

(rnd > 0).sum()         # counts number of positive values
(rnd > 0).any()         # checks if any value its True
(rnd > 0).all()        # checks if all values are True

# random numbers
np.random.seed(12234)      # set the seed
np.random.rand(2, 3)       # 2 X 3 matrix in [0, 1]
np.random.randn(1)        # random normals (mean 0, sd 1)
np.random.randint(0, 2, 10)  # 10 randomly picked 0 or 1




4.035967378638166


array([[0.00630595, 0.20303476, 0.76478993],
       [0.55513384, 0.74358546, 0.93777808]])

In [161]:
# task 4.8 Exercises
# Given array
new = np.random.randn(4, 2) #random normals in 4X2 array

# for each column find the row index of the minimum value.

print(new)
# print(new[:, 0:1])
# print(new[:, 1])

print(new[:, 0:1].argmin())  
print(new[:,1].argmin())

# write a function standarize (x) that return an array whose columns are centered and scaled (by std-dev)
#Totol time of the script: (o minutes 0.0007 seconds)
# def standardize(new):
def standardize():
    std1= np.std(new)
    mean1 = new.mean()
    z= ((new)-mean1)/std1
    print(z)
standardize()

    



[[ 0.07889756 -0.40969141]
 [-1.44384363  0.51754543]
 [-2.39099691 -0.70984446]
 [-0.25910079 -0.51549174]]
2
2
[[ 0.84706423  0.27261965]
 [-0.9432554   1.36279199]
 [-2.05684392 -0.08027676]
 [ 0.44967229  0.14822792]]


In [176]:
'''
Lists of cammands that are useful and were not included in the exercise
1. np.indices()
Indices()  creates a set of arrays stacked as one higher dimession array, one per dimension with each representing variation in that dimension. 
2.np.cos(x[, out]) = ufunc ‘cos’) : This mathematical function helps user to calculate trignmetric cosine for all x(being the array elements)
3.np.round_(arr, decimals = 0, out = None) : This mathematical function round an array to the given number of decimals.
4.np.transpose, it changes the order of an array from (r,c) tp (c,r).
5.np.divide(arr1, arr2) it divides one array to another

'''

data = "1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter=",")

NameError: name 'StringIO' is not defined